name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install tmux
        run: sudo apt-get install -y tmux

      - name: Run TUI tests inside tmux
        run: tmux new-session -d 'make ci' && sleep 2